dateModified: 1595602882
email:
  fromEmail: $SYSTEM_EMAIL_ADDRESS
  fromName: $SENDER_NAME
  replyToEmail: $REPLY_TO_ADDRESS
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  71d53f95-1c79-4cf9-9bf3-bff04b506bea:
    name: Common
fields:
  b301e0d5-b8c7-46b2-9798-5765e883999d:
    contentColumnType: text
    fieldGroup: 71d53f95-1c79-4cf9-9bf3-bff04b506bea
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
graphql:
  scopes:
    55645ee2-d4ea-4c4b-9bd2-e73354e65b82:
      name: 'Public Schema'
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  540a3332-e95d-40d1-a4fb-e5b9c7cd28e9:
    enableVersioning: false
    entryTypes:
      f02ca8b5-a06f-40e8-87ef-74d47855121b:
        fieldLayouts:
          a560c765-84be-4e50-a13e-08f14dad1367:
            tabs:
              -
                fields:
                  b301e0d5-b8c7-46b2-9798-5765e883999d:
                    required: false
                    sortOrder: 1
                name: Common
                sortOrder: 1
        handle: blog
        hasTitleField: true
        name: Blog
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: blog
    name: Blog
    previewTargets: null
    propagationMethod: all
    siteSettings:
      5175a4de-61e4-46da-a275-8d5e41e17cb6:
        enabledByDefault: true
        hasUrls: true
        template: blog/_entry
        uriFormat: 'blog/{slug}'
    type: channel
siteGroups:
  3dcc8a9c-1af6-4cb7-b4f3-9102d6f5f013:
    name: 'Craft Starter'
sites:
  5175a4de-61e4-46da-a275-8d5e41e17cb6:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: 'Craft Starter'
    primary: true
    siteGroup: 3dcc8a9c-1af6-4cb7-b4f3-9102d6f5f013
    sortOrder: 1
system:
  edition: solo
  live: true
  name: $SYSTEM_NAME
  schemaVersion: 3.4.11
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  7eba656c-f4b4-4871-ba1d-85680617f5d3:
    handle: images
    hasUrls: true
    name: images
    settings:
      path: $ASSETS_FILE_SYSTEM_PATH
    sortOrder: 1
    type: craft\volumes\Local
    url: $ASSETS_BASE_URL
